### ISSUE TITLE
Linkedlist returns only seg faults

### ISSUE THREAD

**Issue by YjangWynter** [adriancooper13/CS1_SI#1]
I tried following your example during the SI session and ran your code on both my Linux and Windows machine and it only returns segmentation faults. I used the alternatives to the main functions too, so it's an issue with the code, but I don't know anything about this stuff since I'm learning

**Comment by adriancooper13** [comment]
Hey Yjang,
Thanks for reaching out. Everything seems to work fine on my system. Did you copy and paste all the code exactly? If there’s time on Tuesday we can look through the code and see what the issue could be.

**Comment by adriancooper13** [comment]
Hey Yjang,
Uploaded to Eustis and ran there. Set head = NULL in main() and seems to work fine now on eustis. Unfortunately I don't have a Windows computer to test on, but I uploaded the file with this change. Let me know if there are any other issues.
- Adrian
